### ISSUE TITLE
sbt assembly fails

### ISSUE THREAD

**Issue by machawk1** [helgeho/Web2Warc#6]
I am trying to use Web2Warc from the repo source (8e8e309bdeca61e434288d4ed2ba426218b685ed) and am running into issues getting started.

```
$ git clone https://github.com/helgeho/Web2Warc
$ cd Web2Warc
$ cd project (per the README setup instructions)
$ sbt assembly
[info] Updated file /private/tmp/Web2Warc/project/project/build.properties: set sbt.version to 1.2.6
[info] Loading project definition from /private/tmp/Web2Warc/project/project
[info] Updating ProjectRef(uri("file:/private/tmp/Web2Warc/project/project/"), "project-build")...
[info] Done updating.
[info] Loading settings for project project from assembly.sbt,plugins.sbt ...
[info] Set current project to project (in build file:/private/tmp/Web2Warc/project/)
[error] Not a valid command: assembly
[error] Not a valid project ID: assembly
[error] Expected ':'
[error] Not a valid key: assembly
[error] assembly
[error]         ^
$
```

No `web2warc-assembly-1.0.jar` appears to have been created. I am using Scala 2.12.7 on macOS 10.14.1. Please advise.

**Comment by helgeho** [comment]
Hey Mat, I admit the instructions are a bit confusing here, I just did not realize there is a folder called `project` when I wrote this. Just omit the second `cd`, _project folder_ here refers to the one that you cloned the repo to. Sorry about that, hope this helps!

**Comment by machawk1** [comment]
Helge, I actually tried running it from the root of the repo first (as you described) and only then figured I was misinterpreting the instructions. I receive a different error when running `sbt assembly` from the root:
```
$ git clone https://github.com/helgeho/Web2Warc
$ cd Web2Warc
$ java --version
java 11.0.1 2018-10-16 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.1+13-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.1+13-LTS, mixed mode)
$ sbt assembly
error: error while loading package, Missing dependency 'object java.lang.Object in compiler mirror', required by /Users/machawk1/.sbt/boot/scala-2.10.6/lib/scala-library.jar(scala/package.class)
error: error while loading package, Missing dependency 'object java.lang.Object in compiler mirror', required by /Users/machawk1/.sbt/boot/scala-2.10.6/lib/scala-library.jar(scala/runtime/package.class)
scala.reflect.internal.MissingRequirementError: object java.lang.Object in compiler mirror not found.
	at scala.reflect.internal.MissingRequirementError$.signal(MissingRequirementError.scala:16)
	at scala.reflect.internal.MissingRequirementError$.notFound(MissingRequirementError.scala:17)
	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:48)
	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:40)
	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:40)
	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:61)
	at scala.reflect.internal.Mirrors$RootsBase.getClassByName(Mirrors.scala:99)
	at scala.reflect.internal.Mirrors$RootsBase.getRequiredClass(Mirrors.scala:102)
	at scala.reflect.internal.Definitions$DefinitionsClass.ObjectClass$lzycompute(Definitions.scala:264)
	at scala.reflect.internal.Definitions$DefinitionsClass.ObjectClass(Definitions.scala:264)
	at scala.reflect.internal.Definitions$DefinitionsClass.AnyRefClass$lzycompute(Definitions.scala:263)
	at scala.reflect.internal.Definitions$DefinitionsClass.AnyRefClass(Definitions.scala:263)
	at scala.reflect.internal.Definitions$DefinitionsClass.specialPolyClass(Definitions.scala:1120)
	at scala.reflect.internal.Definitions$DefinitionsClass.RepeatedParamClass$lzycompute(Definitions.scala:407)
	at scala.reflect.internal.Definitions$DefinitionsClass.RepeatedParamClass(Definitions.scala:407)
	at scala.reflect.internal.Definitions$DefinitionsClass.syntheticCoreClasses$lzycompute(Definitions.scala:1154)
	at scala.reflect.internal.Definitions$DefinitionsClass.syntheticCoreClasses(Definitions.scala:1152)
	at scala.reflect.internal.Definitions$DefinitionsClass.symbolsNotPresentInBytecode$lzycompute(Definitions.scala:1196)
	at scala.reflect.internal.Definitions$DefinitionsClass.symbolsNotPresentInBytecode(Definitions.scala:1196)
	at scala.reflect.internal.Definitions$DefinitionsClass.init(Definitions.scala:1261)
	at scala.tools.nsc.Global$Run.<init>(Global.scala:1290)
	at sbt.compiler.Eval$$anon$1.<init>(Eval.scala:141)
	at sbt.compiler.Eval.run$lzycompute$1(Eval.scala:141)
	at sbt.compiler.Eval.run$1(Eval.scala:141)
	at sbt.compiler.Eval.unlinkAll$1(Eval.scala:144)
	at sbt.compiler.Eval.evalCommon(Eval.scala:153)
	at sbt.compiler.Eval.eval(Eval.scala:96)
	at sbt.EvaluateConfigurations$.evaluateDslEntry(EvaluateConfigurations.scala:177)
	at sbt.EvaluateConfigurations$$anonfun$9.apply(EvaluateConfigurations.scala:117)
	at sbt.EvaluateConfigurations$$anonfun$9.apply(EvaluateConfigurations.scala:115)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at sbt.EvaluateConfigurations$.evaluateSbtFile(EvaluateConfigurations.scala:115)
	at sbt.Load$.sbt$Load$$loadSettingsFile$1(Load.scala:775)
	at sbt.Load$$anonfun$sbt$Load$$memoLoadSettingsFile$1$1.apply(Load.scala:781)
	at sbt.Load$$anonfun$sbt$Load$$memoLoadSettingsFile$1$1.apply(Load.scala:780)
	at scala.collection.MapLike$class.getOrElse(MapLike.scala:128)
	at scala.collection.AbstractMap.getOrElse(Map.scala:58)
	at sbt.Load$.sbt$Load$$memoLoadSettingsFile$1(Load.scala:780)
	at sbt.Load$$anonfun$loadFiles$1$2.apply(Load.scala:788)
	at sbt.Load$$anonfun$loadFiles$1$2.apply(Load.scala:788)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at sbt.Load$.loadFiles$1(Load.scala:788)
	at sbt.Load$.discoverProjects(Load.scala:799)
	at sbt.Load$.discover$1(Load.scala:585)
	at sbt.Load$.sbt$Load$$loadTransitive(Load.scala:633)
	at sbt.Load$$anonfun$loadUnit$1.sbt$Load$$anonfun$$loadProjects$1(Load.scala:482)
	at sbt.Load$$anonfun$loadUnit$1$$anonfun$40.apply(Load.scala:485)
	at sbt.Load$$anonfun$loadUnit$1$$anonfun$40.apply(Load.scala:485)
	at sbt.Load$.timed(Load.scala:1025)
	at sbt.Load$$anonfun$loadUnit$1.apply(Load.scala:485)
	at sbt.Load$$anonfun$loadUnit$1.apply(Load.scala:459)
	at sbt.Load$.timed(Load.scala:1025)
	at sbt.Load$.loadUnit(Load.scala:459)
	at sbt.Load$$anonfun$25$$anonfun$apply$14.apply(Load.scala:311)
	at sbt.Load$$anonfun$25$$anonfun$apply$14.apply(Load.scala:310)
	at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:91)
	at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:90)
	at sbt.BuildLoader.apply(BuildLoader.scala:140)
	at sbt.Load$.loadAll(Load.scala:365)
	at sbt.Load$.loadURI(Load.scala:320)
	at sbt.Load$.load(Load.scala:316)
	at sbt.Load$.load(Load.scala:305)
	at sbt.Load$$anonfun$4.apply(Load.scala:146)
	at sbt.Load$$anonfun$4.apply(Load.scala:146)
	at sbt.Load$.timed(Load.scala:1025)
	at sbt.Load$.apply(Load.scala:146)
	at sbt.Load$.buildPluginDefinition(Load.scala:886)
	at sbt.Load$.buildPlugins(Load.scala:852)
	at sbt.Load$.plugins(Load.scala:840)
	at sbt.Load$$anonfun$loadUnit$1$$anonfun$34.apply(Load.scala:465)
	at sbt.Load$$anonfun$loadUnit$1$$anonfun$34.apply(Load.scala:465)
	at sbt.Load$.timed(Load.scala:1025)
	at sbt.Load$$anonfun$loadUnit$1.apply(Load.scala:464)
	at sbt.Load$$anonfun$loadUnit$1.apply(Load.scala:459)
	at sbt.Load$.timed(Load.scala:1025)
	at sbt.Load$.loadUnit(Load.scala:459)
	at sbt.Load$$anonfun$25$$anonfun$apply$14.apply(Load.scala:311)
	at sbt.Load$$anonfun$25$$anonfun$apply$14.apply(Load.scala:310)
	at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:91)
	at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:90)
	at sbt.BuildLoader.apply(BuildLoader.scala:140)
	at sbt.Load$.loadAll(Load.scala:365)
	at sbt.Load$.loadURI(Load.scala:320)
	at sbt.Load$.load(Load.scala:316)
	at sbt.Load$.load(Load.scala:305)
	at sbt.Load$$anonfun$4.apply(Load.scala:146)
	at sbt.Load$$anonfun$4.apply(Load.scala:146)
	at sbt.Load$.timed(Load.scala:1025)
	at sbt.Load$.apply(Load.scala:146)
	at sbt.Load$.defaultLoad(Load.scala:39)
	at sbt.BuiltinCommands$.liftedTree1$1(Main.scala:503)
	at sbt.BuiltinCommands$.doLoadProject(Main.scala:503)
	at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:495)
	at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:495)
	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:59)
	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:59)
	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
	at sbt.Command$.process(Command.scala:93)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
	at sbt.State$$anon$1.runCmd$1(State.scala:183)
	at sbt.State$$anon$1.process(State.scala:187)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.MainLoop$.next(MainLoop.scala:96)
	at sbt.MainLoop$.run(MainLoop.scala:89)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:68)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:63)
	at sbt.Using.apply(Using.scala:24)
	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:63)
	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:46)
	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:30)
	at sbt.MainLoop$.runLogged(MainLoop.scala:22)
	at sbt.StandardMain$.runManaged(Main.scala:61)
	at sbt.xMain.run(Main.scala:35)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
	at xsbt.boot.Launch$.run(Launch.scala:109)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
	at xsbt.boot.Launch$.launch(Launch.scala:117)
	at xsbt.boot.Launch$.apply(Launch.scala:18)
	at xsbt.boot.Boot$.runImpl(Boot.scala:56)
	at xsbt.boot.Boot$.main(Boot.scala:18)
	at xsbt.boot.Boot.main(Boot.scala)
[error] scala.reflect.internal.MissingRequirementError: object java.lang.Object in compiler mirror not found.
[error] Use 'last' for the full log.
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? 
```

**Comment by helgeho** [comment]
I just tried it myself and it compiled just fine... After searching for that exception you get, it seems like there might be some incompatibility between your Scala version and Java >9, could you please try it with Java 8 (1.8)? You can just temporarily change your `JAVA_HOME` env variable

**Comment by machawk1** [comment]
@helgeho That worked for me. I figured the Java version might be the culprit based on experience with Heritrix and OWB. Perhaps the Java caveat/requirement should be noted in the README.

```
$ java -version
java version "1.8.0_192"
Java(TM) SE Runtime Environment (build 1.8.0_192-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.192-b12, mixed mode)
$ sbt assembly
[info] Loading project definition from /private/tmp/Web2Warc/project
[info] Set current project to web2warc (in build file:/private/tmp/Web2Warc/)
[info] Updating {file:/private/tmp/Web2Warc/}web2warc...
[info] Resolving org.sonatype.oss#oss-parent;9 ...
[info] downloading https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.11.11/scala-library-2.11.11.jar ...
[info] 	[SUCCESSFUL ] org.scala-lang#scala-library;2.11.11!scala-library.jar (407ms)
[info] downloading https://repo1.maven.org/maven2/org/jsoup/jsoup/1.8.3/jsoup-1.8.3.jar ...
[info] 	[SUCCESSFUL ] org.jsoup#jsoup;1.8.3!jsoup.jar (55ms)
[info] downloading https://repo1.maven.org/maven2/commons-io/commons-io/2.4/commons-io-2.4.jar ...
[info] 	[SUCCESSFUL ] commons-io#commons-io;2.4!commons-io.jar (45ms)
[info] downloading https://repo1.maven.org/maven2/org/apache/httpcomponents/httpclient/4.5.1/httpclient-4.5.1.jar ...
[info] 	[SUCCESSFUL ] org.apache.httpcomponents#httpclient;4.5.1!httpclient.jar (69ms)
[info] downloading https://repo1.maven.org/maven2/org/netpreserve/commons/webarchive-commons/1.1.5/webarchive-commons-1.1.5.jar ...
[info] 	[SUCCESSFUL ] org.netpreserve.commons#webarchive-commons;1.1.5!webarchive-commons.jar (64ms)
[info] downloading https://repo1.maven.org/maven2/org/apache/httpcomponents/httpcore/4.4.3/httpcore-4.4.3.jar ...
[info] 	[SUCCESSFUL ] org.apache.httpcomponents#httpcore;4.4.3!httpcore.jar (54ms)
[info] downloading https://repo1.maven.org/maven2/commons-logging/commons-logging/1.2/commons-logging-1.2.jar ...
[info] 	[SUCCESSFUL ] commons-logging#commons-logging;1.2!commons-logging.jar (44ms)
[info] downloading https://repo1.maven.org/maven2/commons-codec/commons-codec/1.9/commons-codec-1.9.jar ...
[info] 	[SUCCESSFUL ] commons-codec#commons-codec;1.9!commons-codec.jar (53ms)
[info] downloading https://repo1.maven.org/maven2/junit/junit/3.8.1/junit-3.8.1.jar ...
[info] 	[SUCCESSFUL ] junit#junit;3.8.1!junit.jar (46ms)
[info] downloading https://repo1.maven.org/maven2/com/google/guava/guava/17.0/guava-17.0.jar ...
[info] 	[SUCCESSFUL ] com.google.guava#guava;17.0!guava.jar(bundle) (130ms)
[info] downloading https://repo1.maven.org/maven2/org/json/json/20131018/json-20131018.jar ...
[info] 	[SUCCESSFUL ] org.json#json;20131018!json.jar (42ms)
[info] downloading https://repo1.maven.org/maven2/org/htmlparser/htmlparser/1.6/htmlparser-1.6.jar ...
[info] 	[SUCCESSFUL ] org.htmlparser#htmlparser;1.6!htmlparser.jar (56ms)
[info] downloading https://repo1.maven.org/maven2/com/googlecode/juniversalchardet/juniversalchardet/1.0.3/juniversalchardet-1.0.3.jar ...
[info] 	[SUCCESSFUL ] com.googlecode.juniversalchardet#juniversalchardet;1.0.3!juniversalchardet.jar (52ms)
[info] downloading https://repo1.maven.org/maven2/commons-httpclient/commons-httpclient/3.1/commons-httpclient-3.1.jar ...
[info] 	[SUCCESSFUL ] commons-httpclient#commons-httpclient;3.1!commons-httpclient.jar (53ms)
[info] downloading https://repo1.maven.org/maven2/commons-lang/commons-lang/2.5/commons-lang-2.5.jar ...
[info] 	[SUCCESSFUL ] commons-lang#commons-lang;2.5!commons-lang.jar (53ms)
[info] downloading https://repo1.maven.org/maven2/org/gnu/inet/libidn/1.15/libidn-1.15.jar ...
[info] 	[SUCCESSFUL ] org.gnu.inet#libidn;1.15!libidn.jar (44ms)
[info] downloading https://repo1.maven.org/maven2/it/unimi/dsi/dsiutils/2.0.12/dsiutils-2.0.12.jar ...
[info] 	[SUCCESSFUL ] it.unimi.dsi#dsiutils;2.0.12!dsiutils.jar (56ms)
[info] downloading https://repo1.maven.org/maven2/joda-time/joda-time/1.6/joda-time-1.6.jar ...
[info] 	[SUCCESSFUL ] joda-time#joda-time;1.6!joda-time.jar (63ms)
[info] downloading https://repo1.maven.org/maven2/it/unimi/dsi/fastutil/6.5.2/fastutil-6.5.2.jar ...
[info] 	[SUCCESSFUL ] it.unimi.dsi#fastutil;6.5.2!fastutil.jar (738ms)
[info] downloading https://repo1.maven.org/maven2/com/martiansoftware/jsap/2.1/jsap-2.1.jar ...
[info] 	[SUCCESSFUL ] com.martiansoftware#jsap;2.1!jsap.jar (45ms)
[info] downloading https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.2/slf4j-api-1.7.2.jar ...
[info] 	[SUCCESSFUL ] org.slf4j#slf4j-api;1.7.2!slf4j-api.jar (43ms)
[info] downloading https://repo1.maven.org/maven2/log4j/log4j/1.2.17/log4j-1.2.17.jar ...
[info] 	[SUCCESSFUL ] log4j#log4j;1.2.17!log4j.jar(bundle) (61ms)
[info] downloading https://repo1.maven.org/maven2/commons-configuration/commons-configuration/1.8/commons-configuration-1.8.jar ...
[info] 	[SUCCESSFUL ] commons-configuration#commons-configuration;1.8!commons-configuration.jar (51ms)
[info] downloading https://repo1.maven.org/maven2/commons-collections/commons-collections/3.2.1/commons-collections-3.2.1.jar ...
[info] 	[SUCCESSFUL ] commons-collections#commons-collections;3.2.1!commons-collections.jar (62ms)
[info] downloading https://repo1.maven.org/maven2/org/apache/commons/commons-math3/3.1.1/commons-math3-3.1.1.jar ...
[info] 	[SUCCESSFUL ] org.apache.commons#commons-math3;3.1.1!commons-math3.jar (116ms)
[info] downloading https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.11.11/scala-compiler-2.11.11.jar ...
[info] 	[SUCCESSFUL ] org.scala-lang#scala-compiler;2.11.11!scala-compiler.jar (617ms)
[info] downloading https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.11.11/scala-reflect-2.11.11.jar ...
[info] 	[SUCCESSFUL ] org.scala-lang#scala-reflect;2.11.11!scala-reflect.jar (210ms)
[info] downloading https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.11/1.0.5/scala-xml_2.11-1.0.5.jar ...
[info] 	[SUCCESSFUL ] org.scala-lang.modules#scala-xml_2.11;1.0.5!scala-xml_2.11.jar(bundle) (66ms)
[info] downloading https://repo1.maven.org/maven2/org/scala-lang/modules/scala-parser-combinators_2.11/1.0.4/scala-parser-combinators_2.11-1.0.4.jar ...
[info] 	[SUCCESSFUL ] org.scala-lang.modules#scala-parser-combinators_2.11;1.0.4!scala-parser-combinators_2.11.jar(bundle) (57ms)
[info] downloading https://repo1.maven.org/maven2/jline/jline/2.14.3/jline-2.14.3.jar ...
[info] 	[SUCCESSFUL ] jline#jline;2.14.3!jline.jar (50ms)
[info] Done updating.
[warn] Found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[warn] 
[warn] 	* com.google.guava:guava:17.0 is selected over 14.0-rc2
[warn] 	    +- org.netpreserve.commons:webarchive-commons:1.1.5   (depends on 17.0)
[warn] 	    +- it.unimi.dsi:dsiutils:2.0.12                       (depends on 14.0-rc2)
[warn] 
[warn] Run 'evicted' to see detailed eviction warnings
[info] Compiling 22 Scala sources to /private/tmp/Web2Warc/target/scala-2.11/classes...
[info] 'compiler-interface' not yet compiled for Scala 2.11.11. Compiling...
[info]   Compilation completed in 17.939 s
[info] Including: slf4j-api-1.7.2.jar
[info] Including: commons-httpclient-3.1.jar
[info] Including: webarchive-commons-1.1.5.jar
[info] Including: log4j-1.2.17.jar
[info] Including: jsoup-1.8.3.jar
[info] Including: commons-lang-2.5.jar
[info] Including: commons-io-2.4.jar
[info] Including: commons-configuration-1.8.jar
[info] Including: libidn-1.15.jar
[info] Including: dsiutils-2.0.12.jar
[info] Including: httpclient-4.5.1.jar
[info] Including: junit-3.8.1.jar
[info] Including: commons-collections-3.2.1.jar
[info] Including: guava-17.0.jar
[info] Including: fastutil-6.5.2.jar
[info] Including: httpcore-4.4.3.jar
[info] Including: commons-math3-3.1.1.jar
[info] Including: commons-logging-1.2.jar
[info] Including: commons-codec-1.9.jar
[info] Including: json-20131018.jar
[info] Including: htmlparser-1.6.jar
[info] Including: juniversalchardet-1.0.3.jar
[info] Including: joda-time-1.6.jar
[info] Including: jsap-2.1.jar
[info] Merging files...
[warn] Merging 'META-INF/DEPENDENCIES' with strategy 'discard'
[warn] Merging 'META-INF/LICENSE' with strategy 'discard'
[warn] Merging 'META-INF/LICENSE.txt' with strategy 'discard'
[warn] Merging 'META-INF/MANIFEST.MF' with strategy 'discard'
[warn] Merging 'META-INF/NOTICE' with strategy 'discard'
[warn] Merging 'META-INF/NOTICE.txt' with strategy 'discard'
[warn] Merging 'META-INF/README.txt' with strategy 'discard'
[warn] Merging 'META-INF/maven/com.google.guava/guava/pom.properties' with strategy 'discard'
[warn] Merging 'META-INF/maven/com.google.guava/guava/pom.xml' with strategy 'discard'
[warn] Merging 'META-INF/maven/com.googlecode.juniversalchardet/juniversalchardet/pom.properties' with strategy 'discard'
[warn] Merging 'META-INF/maven/com.googlecode.juniversalchardet/juniversalchardet/pom.xml' with strategy 'discard'
[warn] Merging 'META-INF/maven/commons-codec/commons-codec/pom.properties' with strategy 'discard'
[warn] Merging 'META-INF/maven/commons-codec/commons-codec/pom.xml' with strategy 'discard'
[warn] Merging 'META-INF/maven/commons-collections/commons-collections/pom.properties' with strategy 'discard'
[warn] Merging 'META-INF/maven/commons-collections/commons-collections/pom.xml' with strategy 'discard'
[warn] Merging 'META-INF/maven/commons-configuration/commons-configuration/pom.properties' with strategy 'discard'
[warn] Merging 'META-INF/maven/commons-configuration/commons-configuration/pom.xml' with strategy 'discard'
[warn] Merging 'META-INF/maven/commons-io/commons-io/pom.properties' with strategy 'discard'
[warn] Merging 'META-INF/maven/commons-io/commons-io/pom.xml' with strategy 'discard'
[warn] Merging 'META-INF/maven/commons-lang/commons-lang/pom.properties' with strategy 'discard'
[warn] Merging 'META-INF/maven/commons-lang/commons-lang/pom.xml' with strategy 'discard'
[warn] Merging 'META-INF/maven/commons-logging/commons-logging/pom.properties' with strategy 'discard'
[warn] Merging 'META-INF/maven/commons-logging/commons-logging/pom.xml' with strategy 'discard'
[warn] Merging 'META-INF/maven/log4j/log4j/pom.properties' with strategy 'discard'
[warn] Merging 'META-INF/maven/log4j/log4j/pom.xml' with strategy 'discard'
[warn] Merging 'META-INF/maven/org.apache.commons/commons-math3/pom.properties' with strategy 'discard'
[warn] Merging 'META-INF/maven/org.apache.commons/commons-math3/pom.xml' with strategy 'discard'
[warn] Merging 'META-INF/maven/org.apache.httpcomponents/httpclient/pom.properties' with strategy 'discard'
[warn] Merging 'META-INF/maven/org.apache.httpcomponents/httpclient/pom.xml' with strategy 'discard'
[warn] Merging 'META-INF/maven/org.apache.httpcomponents/httpcore/pom.properties' with strategy 'discard'
[warn] Merging 'META-INF/maven/org.apache.httpcomponents/httpcore/pom.xml' with strategy 'discard'
[warn] Merging 'META-INF/maven/org.gnu.inet/libidn/pom.properties' with strategy 'discard'
[warn] Merging 'META-INF/maven/org.gnu.inet/libidn/pom.xml' with strategy 'discard'
[warn] Merging 'META-INF/maven/org.json/json/pom.properties' with strategy 'discard'
[warn] Merging 'META-INF/maven/org.json/json/pom.xml' with strategy 'discard'
[warn] Merging 'META-INF/maven/org.jsoup/jsoup/pom.properties' with strategy 'discard'
[warn] Merging 'META-INF/maven/org.jsoup/jsoup/pom.xml' with strategy 'discard'
[warn] Merging 'META-INF/maven/org.netpreserve.commons/webarchive-commons/pom.properties' with strategy 'discard'
[warn] Merging 'META-INF/maven/org.netpreserve.commons/webarchive-commons/pom.xml' with strategy 'discard'
[warn] Merging 'META-INF/maven/org.slf4j/slf4j-api/pom.properties' with strategy 'discard'
[warn] Merging 'META-INF/maven/org.slf4j/slf4j-api/pom.xml' with strategy 'discard'
[warn] Strategy 'discard' was applied to 41 files
[info] Packaging /private/tmp/Web2Warc/target/scala-2.11/web2warc-assembly-1.1.jar ...
[info] Done packaging.
[success] Total time: 53 s, completed Nov 7, 2018 9:41:17 AM
$ ls target/scala-2.11/
classes				resolution-cache		web2warc-assembly-1.1.jar
```
